version: '3'
services:
  beduka-mysql:
    image: postgres
    container_name: educai-db
    tty: true
    ports:
      - '3305:3306'
    environment:
      POSTGRES_ROOT_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DATABASE: educai-db
