version: '3'
services:
  educai-db:
    image: postgres
    container_name: educai-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: educai-db
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
